version: '3'

volumes:
  base_node_modules:
  client_node_modules:
  server_node_modules:

services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h localhost -u test -ptest
      interval: 10s
      timeout: 5s
      retries: 3

  node:
    build:
      context: .
      dockerfile: docker/dev/node/Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - '3000:5173'
      - '8080:3000'
    depends_on:
      db:
        condition: service_healthy