version: '3'

volumes:
  base_node_modules:
  client_node_modules:
  server_node_modules:

services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  node:
    build:
      context: .
      dockerfile: docker/dev/node/Dockerfile
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - '3000:5173'
      - '8080:3000'
    volumes:
      - ./:/app/
      - base_node_modules:/app/node_modules/
      - client_node_modules:/app/node/client/node_modules/
      - server_node_modules:/app/node/server/node_modules/
    depends_on:
      - db