version: '3.7'

networks:
  nginx-network:
    external:
      name: nginx-network

services:
  node:
    build:
      context: .
      dockerfile: docker/prod/node/Dockerfile
    restart: always
    ports:
      - "8080:3000"
    networks:
      - nginx-network
