name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Base Docker
        run: |
          docker-compose up -d

      - name: Build Cypress Docker
        run: |
          docker build -t cypress -f docker/dev/cypress/Dockerfile .

      - name: Run Cypress Docker
        run: |
          docker run --rm --network="host" -e CYPRESS_BASE_URL=http://localhost:3000 cypress

      - name: Stop Base Docker
        run: |
          docker-compose down
